language: bash

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

# Disable the default submodule logic
git:
  submodules: false

# Check scrips for warnings/errors
script:
  - shellcheck cosmo/parse.cosmo.sh compiler/clementon2.gnu.sh common/check.omni.lib.sh

# Notification settings
notifications:
  slack: meteoswiss-apn:FFUYLitE3BsncqECl4RqlfHP
  email:
    on_success: never
    on_failure: always
